apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURNakNDQWhxZ0F3SUJBZ0lSQU1HWnFxNlpFK1YxT1dHZ3NIcHJBcUl3RFFZSktvWklodmNOQVFFTEJRQXcKSnpFUU1BNEdBMVVFQ2hNSFFWZFRJRVZMVXpFVE1CRUdBMVVFQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpFdwpNRFl4TlRFNU16SmFGdzB6TVRFd01EVXhOVEU1TXpKYU1DY3hFREFPQmdOVkJBb1RCMEZYVXlCRlMxTXhFekFSCkJnTlZCQU1UQ210MVltVnlibVYwWlhNd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUIKQVFDL0dJbklmVkJiWFdDUzNPTFNlaGJibm5RNFJrZzNiMnRsazdIMzVkclZnK0FrNkZOZ0tCdXdxYUs4V3p5MAozdWo4RDIvWjZEZS9rRk1ldy9PY2hLRzRhb0dMWm9aUmZZMStNMzYwN2NqV2g4eFNaUWh1dmFJcnVuWTRmb3FqCkxLS09sUjFxbmZySU5oQUFUVTMzczFGbE1kZzhYRG41TktSQi9uMFJtYys5RitSRzFpa05NUFRNYm9rNi81Sm8Ka2RHMjAyYVZHZ0JMdTRTQ2hMdG56cTUveDZrL3FmN1ErMjgyM2J0cURGT09YcGNaa25XZVo5SnViaysrdjN6bQp0UWU5cW4zVGNXaGtiOXVYMUQ3UXFoVUUxck5IT0FLUHROYm5iU1k1YnE2Ti8zaGNVUDNuRlFrNThJQmlab0pDClVUTjNrT0lTU3kwbW9FUmt5cUJDYjVrWEFnTUJBQUdqV1RCWE1BNEdBMVVkRHdFQi93UUVBd0lDcERBUEJnTlYKSFJNQkFmOEVCVEFEQVFIL01CMEdBMVVkRGdRV0JCUUNSMGVqUUpOcmlCdk8xNW5YRmNVd1ptTEkxakFWQmdOVgpIUkVFRGpBTWdncHJkV0psY201bGRHVnpNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUF6L2UvdWY3STZnKzJECldGK216OExlVEdzUG1vQUo3ZlVnbWdHN1NUK1NxeGxtYnhWekJ5YS9sdjJmdWowS1YzV0FLWUs3NWRhVkFlbW0KTEhsRXhpd0NvUGRJN1ZqOXJSV0NyM1U1dHJyQ3plakFSZkx4clVuaDVBanYySEpNNm1vZXZHSDcvRVN0TC9yMQpxNDRxLzkya0h2RUxoMTF1RFNHbzRIVDNEN2FPenBJS2twWWt6bmtLaXFOZkJiLytsbnU4Y2JvNVFVTEpPanMrCmx2Rm9OM1ZJTFVkS2VFY2doTFZ4aUl4K2h2L3pIZDM2MkljU3hZejhweDFZWjJNZFpJem1XUThqYlpIS2tnM00KeFNJOXBQdmhmaEZxa2FxNWdqNzNjWUVtVnhrMjROQU91QW1pa09rMmZ2N2VJZFlzRFE4N1dSTjdyaEdYTmhkcwp1RHd0VTdzYwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://9CB3EF7E5EE427AEBA7835FF1D8199A2.gr7.us-east-1.eks.amazonaws.com
  name: arn:aws:eks:us-east-1:298599751110:cluster/devops-showcase-cluster
contexts:
- context:
    cluster: arn:aws:eks:us-east-1:298599751110:cluster/devops-showcase-cluster
    user: arn:aws:eks:us-east-1:298599751110:cluster/devops-showcase-cluster
  name: arn:aws:eks:us-east-1:298599751110:cluster/devops-showcase-cluster
current-context: arn:aws:eks:us-east-1:298599751110:cluster/devops-showcase-cluster
kind: Config
users:
- name: arn:aws:eks:us-east-1:298599751110:cluster/devops-showcase-cluster
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - us-east-1
      - eks
      - get-token
      - --cluster-name
      - devops-showcase-cluster
      - --output
      - json
      command: aws
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
